### ISSUE TITLE
sqlalchemy_query `limit` parameter is confusing

### ISSUE THREAD

**Issue by onanypoint** [PrefectHQ/prefect-sqlalchemy#16]
## Description

The current `limit` parameter description is 

> limit: The number of rows to fetch.

As a result calling 

```
sqlalchemy_query(
    "SELECT * FROM customers WHERE name = :name;",
    sqlalchemy_credentials,
    params={"name": "Marvin"},
    limit=3
)
```

might be interpreted as running something like

```
SELECT * 
FROM customers 
WHERE name = Marvin;
LIMIT 3
```

where in reality it seems to be running the full select and then limiting the number of returned rows programmatically.
 
```
SELECT * 
FROM customers 
WHERE name = Marvin;
```

## Expected Behavior

Providing a value for `limit` should limit the query at the database level and not at the client level

OR

The function should not accept a limit value and push the limit / offset behaviour in the query itself

(I can submit a pull request if you think this should/could be fixed)

## Reproduction

I added the logging behaviour in SQLAlchemy to automatically log the ran query

```
import logging
from prefect_sqlalchemy import DatabaseCredentials, AsyncDriver
from prefect_sqlalchemy.database import sqlalchemy_query
from prefect import flow

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

@flow
def sqlalchemy_query_flow():

    sqlalchemy_credentials = DatabaseCredentials(
        driver=AsyncDriver.POSTGRESQL_ASYNCPG,
        username="prefect",
        password="prefect_password",
        database="postgres",
    )

    result = sqlalchemy_query(
        "SELECT * FROM customers WHERE name = :name;",
        sqlalchemy_credentials,
        params={"name": "Marvin"},
        limit=3
    )
    return result

sqlalchemy_query_flow()
```

will log

```
12:13:14.029 | INFO    | prefect.engine - Created flow run 'tough-donkey' for flow 'sqlalchemy-query-flow'
12:13:14.031 | INFO    | Flow run 'tough-donkey' - Using task runner 'ConcurrentTaskRunner'
12:13:14.207 | INFO    | Flow run 'tough-donkey' - Created task run 'sqlalchemy_query-ff7683f9-0' for task 'sqlalchemy_query'
12:13:14.277 | INFO    | sqlalchemy.engine.Engine - select pg_catalog.version()
12:13:14.278 | INFO    | sqlalchemy.engine.Engine - [raw sql] ()
12:13:14.285 | INFO    | sqlalchemy.engine.Engine - select current_schema()
12:13:14.286 | INFO    | sqlalchemy.engine.Engine - [raw sql] ()
12:13:14.296 | INFO    | sqlalchemy.engine.Engine - show standard_conforming_strings
12:13:14.298 | INFO    | sqlalchemy.engine.Engine - [raw sql] ()
12:13:14.306 | INFO    | sqlalchemy.engine.Engine - BEGIN (implicit)
12:13:14.307 | INFO    | sqlalchemy.engine.Engine - SELECT * FROM customers WHERE name = marvin
12:13:14.308 | INFO    | sqlalchemy.engine.Engine - [generated in 0.00128s] ()
12:13:20.583 | INFO    | sqlalchemy.engine.Engine - COMMIT
12:13:20.892 | INFO    | Task run 'sqlalchemy_query-ff7683f9-0' - Finished in state Completed()
12:13:20.921 | INFO    | Flow run 'tough-donkey' - Finished in state Completed('All states completed.')
```

## Environment

`Python 3.9.12`

Prefect 
```
Version:             2.0b8
API version:         0.7.0
Python version:      3.9.12
Git commit:          4b8dfc35
Built:               Fri, Jul 8, 2022 8:53 AM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         hosted
```

`prefect-sqlalchemy==0.1.0`

**Comment by ahuang11** [comment]
Thanks for reporting this; I agree with you that it's confusing. I'm leaning towards removing limit since I am not too sure if it's possible to operate on the database level (besides doing `query += "LIMIT 5"` which seems prone to error.)

My other solution is to either provide better docs (e.g. `limit: The number of rows to fetch after the query is executed`) or rename limit to `fetch_limit`.

@desertaxle thoughts?

**Comment by ahuang11** [comment]
Another consideration from https://www.sqltutorial.org/sql-limit/
"Not all database systems support the LIMIT clause. Therefore, the LIMIT clause is available only in some database systems only such as [MySQL](http://www.mysqltutorial.org/mysql-limit.aspx), [PostgreSQL](http://www.postgresqltutorial.com/postgresql-limit/), [SQLite](http://www.sqlitetutorial.net/sqlite-limit/), Sybase SQL Anywhere, and HSQLDB. If you use SQL Server, you can use the [SELECT TOP](https://www.sqlservertutorial.net/sql-server-basics/sql-server-select-top/) instead."

So many keeping fetchmany is probably necessary. We can just improve the docs.
