### ISSUE TITLE
Password visible in block configuration

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect-sqlalchemy#42]
When using the new SQLAlchemyConnector to create a block configuration the password is revealed in clear text in the front end:

![image](https://user-images.githubusercontent.com/18382402/214257589-efb9cb73-0887-4ee8-a40a-86cb20c68b19.png)

This causes a serious security flaw.

**Comment by ahuang11** [comment]
Thanks for reporting this. This is fixed on the UI now. Please reopen if you still encounter this.
![image](https://user-images.githubusercontent.com/15331990/217620196-a21c02d5-96e0-4260-b7e8-50cd80ba1631.png)
