### ISSUE TITLE
SqlAlchemyConnector.fetch_all throws exception

### ISSUE THREAD

**Issue by tsteijvers** [PrefectHQ/prefect-sqlalchemy#48]
A sample illustrates the problem:
```
with SqlAlchemyConnector(connection_info=ConnectionComponents(<stuff goes here>)) as connector:
    connector.fetch_all("select * from mytable")
```
This fails since 0.2.3 because that version introduced lazy loading of the engine. In the [PR46](https://github.com/PrefectHQ/prefect-sqlalchemy/pull/46) you can see that `self._unique_results = {}` has been moved into `get_engine`. However, when calling `fetch_all` the [validation of the input_hash](https://github.com/PrefectHQ/prefect-sqlalchemy/blob/70f7faa195ab1f899282663af9412bc72db17d5e/prefect_sqlalchemy/database.py#L524) fails because it is executed before `get_engine` has been called. Therefore `self._unique_results` is still  uninitialized.

# Expectation / Proposal
Move the initialization of `self._unique_results` back to `block_initialization`.

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-sqlalchemy/#contributing) a pull request to resolve this!

**Comment by ahuang11** [comment]
Thank you for reporting this!
