### ISSUE TITLE
Update tests for SQLAlchemy 2

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-sqlalchemy#59]
# Expectation / Proposal
The tests have started failing since SQLAlchmey 2 was released. We don't expect any functionality changes due to SQLAlchemy 2, but we should update the tests.

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-sqlalchemy/#contributing) a pull request to resolve this!

**Comment by obendidi** [comment]
Hello, I've started a PR
feel free to have a look: https://github.com/PrefectHQ/prefect-sqlalchemy/pull/70
